version: '3'

networks:
    rosdocker:
      driver: bridge

services:
    ultrabot_stm:
        build: .
        container_name: ultrabot_stm
        hostname: ultrabot_stm
        working_dir: /root/catkin_ws
        privileged: true
        environment:
            - UDEV=1
        devices:
            - '/dev:/dev'
        depends_on:
            - rosmaster
        networks: 
            - rosdocker
        environment:
            - "ROS_HOSTNAME=ultrabot_stm"
            - "ROS_MASTER_URI=http://rosmaster:11311"
        command: roslaunch --wait ultrabot_stm stm.launch
    # ROS MASTER (ROSCORE)
    rosmaster:
        image: ros:noetic-ros-core
        container_name: rosmaster
        hostname: rosmaster
        networks: 
            - rosdocker
        ports:
            - "11311:11311"
        command: roscore